### ISSUE TITLE
Baizen does not conform to spec

### ISSUE THREAD

**Issue by statonjr** [testdouble/baizen#6]
Baizen correctly parses BAI files from Bank of America, but BoA does not conform to the BAI spec. For example, lines in a BAI file that begin with the number 16 should have a maximum of 7 fields. BAI files from Bank of America have 9 fields. BAI files from Wells Fargo correctly implement the spec as far as I can tell.

**Comment by bostonaholic** [comment]
I have creted #7 which more accurately describes the behavior.

**Comment by bostonaholic** [comment]
Fixed by v0.5.1
